### ISSUE TITLE
设置hint没用了

### ISSUE THREAD

**Issue by protectedMan** [ParfoisMeng/DecimalTextView#1]

**Comment by ParfoisMeng** [comment]
@protectedMan 因为代码内部操作的是text文本，如果没有的话会被默认格式化成数字0，但你可以在代码里调用settext方法可以跳过格式化文本的过程。等我之后有时间会把hint的问题找个方法解决一下

**Comment by ParfoisMeng** [comment]
@protectedMan 抱歉隔了这么久。可以试一下1.0.0。
